### ISSUE TITLE
I can't edit my save file

### ISSUE THREAD

**Issue by logouthere** [skynetDE/VaultEditor#1]
---------------------------
Error when Loading
---------------------------
Invalid Vault Save
---------------------------
OK   
---------------------------

My save is:
1. Play FO Shelter normally.
2. Found http://dinoz.mobi/shelter-editor/ and used it.
3. Have some fun.
4. Tried to use http://dinoz.mobi/shelter-editor/ , browser freezed.
5. Found your tool, download v1.3 tool and select my save.
6. Error!

I'll appreciate if you take a look at my save.
Please email to 
vaultedit@sigaint.org
(or give me your email addr)so I can share my save safely.

Vault1.7z (2MB)

**Comment by codengine** [comment]
Hey there,
is there a VaultEditor.log at the applications folder? If so, could you attach it please?

**Comment by logouthere** [comment]
> VaultEditor.log at the applications folder

No, I can't find it. When I open "VaultEditor.exe" and select my save, it shows an error above, nothing more.

**Comment by logouthere** [comment]
I also searched C:\Users\(user)\AppData\*

**Comment by logouthere** [comment]
nvm, https://rakion99.github.io/shelter-editor/ works.
